fix prisma generate

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -7,7 +7,8 @@ RUN npm install --legacy-peer-deps
 
 COPY . .
 RUN npx prisma generate --schema=src/prisma/schema.prisma
-RUN npx nest build && ls -la dist/
+RUN npx nest build || true
+RUN ls -la && ls -la dist/ || echo "dist folder not found"
 
 EXPOSE 3000
 CMD ["node", "dist/main.js"]
